// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trello_Clone.API.Data;

namespace TrelloClone.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181127082545_CorrectConnections")]
    partial class CorrectConnections
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Trello_Clone.API.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ItemId");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("Trello_Clone.API.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("Favorite");

                    b.Property<bool>("Personal");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Trello_Clone.API.Models.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoardId");

                    b.Property<string>("State");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("Trello_Clone.API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ColumnId");

                    b.Property<int>("MyProperty");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Trello_Clone.API.Models.Attachment", b =>
                {
                    b.HasOne("Trello_Clone.API.Models.Item")
                        .WithMany("Attachments")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("Trello_Clone.API.Models.Column", b =>
                {
                    b.HasOne("Trello_Clone.API.Models.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Trello_Clone.API.Models.Item", b =>
                {
                    b.HasOne("Trello_Clone.API.Models.Column", "Column")
                        .WithMany("Item")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
